### ISSUE TITLE
comments for dev.

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#108]
- [x] 1) Language Menu: The default value of the language menu should show the 'change language icon' (see http://www.languageicon.org/). Find icons in images folder

- [x] 2) The default text of the agreement menu in Colornamer should be 'Do you agree?' or the translated text in other languages

- [x] 3) In Colornamer, there is no audio for Greek and Thai, while other languages (Spanish, German, Russian, Turkish) are missing completely.

- [x] 4) In the description of the Colour Naming Task in Greek, there is a small typo which I corrected in the spreadsheet.

- [x] 5) In the Observer Information the last [Submit] button should be [Αποστολή] in Greek (it is not currently translated)

- [x] 6) The percent of top colournamers in Thank you page is not working properly. For example I named 11 colours and I got a score of 53%, this score should be 11/600(length_array)*100=1.833 rounded to 2%

- [ ] 7) Common fields and parameters in the old and the new database should have the same name.

- [x] 8) Record geolocation in database as described here: https://www.w3schools.com/html/html5_geolocation.asp

- [x] 9) We shouldn't save the IP address

- [x] 10) Record 'language' of experiment in database (it could be different than the language of the browser)

- [x] 11) Record colorData_id in database, each colour name response should have a unique id

- [x] 12) record rgb values of stimulus for each colour name

**Comment by dmylonas** [comment]
@jstutters

**Comment by dmylonas** [comment]
1. Is done by @chrisguttandin

**Comment by jstutters** [comment]
Fixed 2 and 5.

@dmylonas is 4 now resolved?

**Comment by jstutters** [comment]
6 fixed

**Comment by dmylonas** [comment]
Yes 4 is OK

**Comment by jstutters** [comment]
Created a new issue for 7.
