### ISSUE TITLE
Save recordings from the interface to the database

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#11]

**Comment by jstutters** [comment]
@dmylonas could you try the [test site](https://colournaming.jeremah.co.uk) and then download the [participants data CSV](https://colournaming.jeremah.co.uk/admin/participants.csv) and [responses data CSV](https://colournaming.jeremah.co.uk/admin/responses.csv).  I think we might be able to close this now.

**Comment by dmylonas** [comment]
I got an error when I tried to d'l the responses data

**Comment by dmylonas** [comment]
Still, I don't know what info  we save in our database for each participant

**Comment by jstutters** [comment]
The CSVs linked from https://dev.colornaming.net/admin/ show what we're currently recording.

@dmylonas I've emailed you the login information.

**Comment by dmylonas** [comment]
@jstutters I can see the fields but they are empty

**Comment by jstutters** [comment]
You’ll need to do a run through the experiment yourself. The dev version of the site connects to a separate database.

Jon

**Comment by dmylonas** [comment]
For data that we already collect in our old database, we should keep the same variable names and values in the new database so we can combine them in future analysis.

**Comment by dmylonas** [comment]
We do not need the decimals for the recorded response_time. The recording of RT in milliseconds as we are already recording is sufficient.

**Comment by dmylonas** [comment]
@jstutters I do miss accessing the database via mysql

**Comment by dmylonas** [comment]
the agreement with the predictions of Colournamer are not yet saved in the database

**Comment by dmylonas** [comment]
when I am checking the recorded responses in the csv, in the device column I get an 'device.laptop' response, this is happening in many other columns too, do we have to repeat the name of the column within each response?

**Comment by jstutters** [comment]
> @jstutters I do miss accessing the database via mysql

Can look at this after version 1.  If the database is exposed to the host you can tunnel in over ssh and access it using e.g. https://www.pgadmin.org/ or https://www.jetbrains.com/datagrip/.  I don't want to run something like phpmyadmin again - just ends up being a security headache.
