### ISSUE TITLE
Collaborators comments

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#116]
- [x] [Web browser ]
Firefox, Google Chrome, Safari ... OK, the system works.
IE 11 ... doesn't work from the first page of display properties task.

- [x] [Home Page language menu]
The term of language selection in upper right.
   "日本の" -> "日本語"

- [x]  Colornamer needs a description. Add the following description:
'This is a synthetic observer trained by participants’ responses to name each colour in different languages (Mylonas, Stutters, Doval, and MacDonald, 2013). More languages will be added as more data is becoming available.'
It should be translated in other languages. I have added the translations in the spreadsheet.

- [x] Colour Naming Task
1. Add the period "。" in the last sentence.
   "あなたの回答時間は、記録されます" -> "あなたの回答時間は、記録されます 。"
2. Add extra description to improve usability.
(I have added this text in English and Greek and I am waiting for the Russian and Japanese translations) 
I have now added the Russian & Japanese translations.

- [x]  Colour Vision Task
The explanation is written in English not Japanese.

- [x]  Thank you Page
[ Thank you ]
1. Please revise this sentence.
   "以下で、白でのあなたの回答を、黒での最も回答の多かった色名をご覧ください。"
 -> "以下で、あなたの回答(白字)と、最も回答の多かった色名(黒字)をご覧ください。"
(I have updated the translations sheet)
- [x]  Thank you Page 2
2. The predicted colour names (in black) in the Russian version are in English while Colornamer can speak Russian.

**Comment by jstutters** [comment]
Fixed IE 11 compatibility in b4de1f1f5716048ddc9798db4373d8eca49dad9d

**Comment by dmylonas** [comment]
added the additional translations in the spreadsheet

**Comment by jstutters** [comment]
> The predicted colour names (in black) in the Russian version are in English while Colornamer can speak Russian.

This is because we (or I anyway) don't have data for colour centroids in Russian.

> Colornamer needs a description. Add the following description:
'This is a synthetic observer trained by participants’ responses to name each colour in different languages (Mylonas, Stutters, Doval, and MacDonald, 2013). More languages will be added as more data is becoming available.'

Where is this text meant to go?

**Comment by dmylonas** [comment]
_This is because CVwe (or I anyway) don't have data for colour centroids in Russian._
Colornamer can speak Russian, so we do have the centroids and the covariance

**Comment by dmylonas** [comment]
_Where is this text meant to go?_
Can you please add it below the title Colour namer and above the application Colournamer
![colornamer_discription](https://user-images.githubusercontent.com/8037811/36542981-51c7f38a-17da-11e8-8665-23b715eaad17.png)

**Comment by jstutters** [comment]
@dmylonas Can you add the Russian data to Dropbox?

**Comment by dmylonas** [comment]
@jstutters Done

**Comment by jstutters** [comment]
@dmylonas I think we can close this now, can you check https://dev.colornaming.net and confirm?

**Comment by dmylonas** [comment]
@jstutters  Please Add the period "。" in the last sentence of the colour naming task:
"あなたの回答時間は、記録されます" -> "あなたの回答時間は、記録されます 。"
and it is ready to go to the main domains
