### ISSUE TITLE
Keep the ranking/tracking of the old website in multiple languages from Google

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#12]

**Comment by jstutters** [comment]
@dmylonas do you mean the Google analytics?  If so, I guess that's just a matter of copying the relevant bits of the header from the current site.

**Comment by dmylonas** [comment]
our domain-subdomain names in all languages are nicely tracked and listed in Google search. IS it possible to keep these now that we have a dynamic translator?

**Comment by jstutters** [comment]
As with everything google-related it's hard to say but I guess that for other languages google's crawler requests the different language and the site should return that version so in theory it should be ok.

**Comment by jstutters** [comment]
Closing this.  We've kept the same primary domain for search rank and we'll have to rely on Google to figure out the rest.  339383ab019adde277c78dc71bd4388d34d9af1d adds some <link>s which may help.
