### ISSUE TITLE
the hue selection of colorpicker for colournamer is problematic 

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#122]
Users cannot select pink and orange hues

**Comment by dmylonas** [comment]
@jstutters

**Comment by dmylonas** [comment]
or can we just make it wider ?

**Comment by jstutters** [comment]
@dmylonas can you check dev.colornaming.net and confirm if this is fixed there for you?

**Comment by dmylonas** [comment]
@jstutters  the dev.colornaming.net  takes me automatically to colornaming.net

**Comment by jstutters** [comment]
@dmylonas try using the full URL with protocol: https://dev.colornaming.net

**Comment by dmylonas** [comment]
@jstutters  it does work now, cheers! feel free to close it.
