### ISSUE TITLE
Right to Left languages 

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#125]
We need an option that aligns the text from right2left instead of left2right. 
right2left languages:
    Arabic
    Aramaic
    Azeri
    Dhivehi/Maldivian
    Hebrew
    Kurdish (Sorani)
    Persian/Farsi
    Urdu

**Comment by dmylonas** [comment]
at https://dev.colornaming.net/lang/fa
we have a Farsi translation of the experiment that is not aligned properly. It will be nice if we could start bridging the Persian colour language with the other languages of the world.

**Comment by dmylonas** [comment]
@jstutters can you add this 'rtl' rule if the language is one of them: Arabic (ar),  Hebrew (he), Kurdish (ckb), Farsi (fa), Urdu (ur) and I could ask our Persian collaborator to confirm if everything is OK

**Comment by jstutters** [comment]
@dmylonas I've merged a change for this to the develop branch, can you test dev.colornaming.net and let me know if it's ok?

**Comment by jstutters** [comment]
Believe this is now ok.  RTL languages at least do the right thing for blocks of text.  Don't have resources to do a full UI translation.
