### ISSUE TITLE
Move everything to server 

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#15]

**Comment by jstutters** [comment]
I think we should spin up a new linode instance for this - it'll keep the transition short and gives an opportunity to upgrade the node to 64 bit.  @dmylonas is that ok financially?  Once the new site's up we can backup and delete the old node.

**Comment by dmylonas** [comment]
should be OK, at the moment they charge us $20/month, how much extra is going to cost?

**Comment by jstutters** [comment]
The additional server will be the same spec as the current one so $20/month but they charge by the hour now so it shouldn't be that much in total.

**Comment by dmylonas** [comment]
Go for it

**Comment by jstutters** [comment]
Just had a look and I don't think I have access to your linode account so you'll need to bring the server online.

**Comment by jstutters** [comment]
Colournamer is now deployed to magenta.colornaming.com.
