### ISSUE TITLE
Automatic collection of data

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#17]
Don't save the IP but try to save their geographical location (country, city, lat / long, altitude), user-agent (browser, os), client properties (language, local time, screen resolution, colour depth, screen dpi, screen size). The size is also very important - see https://www.infobyip.com/

Device (mobile, pad, pc)?
Model?
https://www.abeautifulsite.net/detecting-mobile-devices-with-javascript

Ambient light?
The other day, I read about the Ambient Light Sensor which is coming to Chrome sooner or later: https://www.chromestatus.com/features/5698781827825664?embed. Firefox has already something called Ambient Light Events (https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events) which we maybe can use to detect the light 

If we cannot get the size of the screen, kind of device/model, we should add them as questions.

**Comment by dmylonas** [comment]
the variable 'created_on' should be 'date_modified' for consistency with the old database or the reverse. The same variable is empty in the participants data and in the responses data is always the same value.

**Comment by dmylonas** [comment]
add geolocation as described here: https://www.w3schools.com/html/html5_geolocation.asp

**Comment by jstutters** [comment]
IP is now removed and geolocation is added.  We can revisit auto-detection of device and ambient light after launch - we have fields in observer information that cover these for the launch.
