### ISSUE TITLE
Update stimuli

### ISSUE THREAD

**Issue by jstutters** [colournaming/colournaming#177]
The size of the stimuli and the tasks will remain the same but we will reduce the number of samples to 226 and present them against a set of 10 chromatic backgrounds. Each observer will name colours only against a single chromatic background selected at random (balanced to guaranteed that all backgrounds will be equally used).

1.	The colour sampling (see colourStimuli_226.csv) of the new experiment (b) will consist of 216 uniformly distributed colour samples in RGB + 10 selected colours (max of PWc for red, green, yellow and blue, plus max L+, L-, M+, M-, S+, and S- specified in sRGB). 
2.	The 10 test backgrounds (see colourBG_10.csv) will be the 10 above selected colours (max of PWc for red, green, yellow and blue, plus max L+, L-, M+, M-, S+, and S- in sRGB).

**Comment by dmylonas** [comment]
Note that we should change stimuli (n=226) only for the new chromatic BG experiment. For the old grey BG experiment stimuli  should remain the same (n=606).
