### ISSUE TITLE
add new publications in research page

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#18]

**Comment by jstutters** [comment]
@dmylonas can you provide the references for these?

**Comment by dmylonas** [comment]
@jstutters  find below the list but I would like to be able to update it myself in the future

Mylonas, D. (2015). The role of psychological primaries in cognitive colour spaces: a cross cultural colour naming study. In Colour Vision Meeting 2015, Colour Group GB.

Mylonas, D., Andrews, J., Griffin L.D. (2016). Variability in free colour naming across the full colour gamut. In AVA Christmas Meeting, London, UK.

Griffin L.D., Mylonas, D. (2016). Why so much talk about “red”? In AVA Christmas Meeting, 
London, UK.

Mylonas, D., MacDonald, L. (2017). Colour Naming for Colour Design. In Colour Design, ed Best, J. Elsevier

Mylonas D. (2017) Where our brain meets the universe. Talk at [Chromophobia: Colour in Architecture](https://designmuseum.org/whats-on/talks-courses-and-workshops/chromophobia-colour-in-architecture). Design Museum, London, UK

Mylonas D. (2017) Features of GREEN colour categories across languages. Talk at The Colour Green meeting, Northern Chapter, Colour Group GB, Newcastle, UK. 

Mylonas, D., MacDonald L., Griffin, L.D. (2017). Differences in Color Naming between British and American English Speakers. In 13th AIC Congress, South Korea.

Griber Y., Paramei G.V., Mylonas, D. (2017). Gender Differences in Russian Colour Naming. In 13th AIC Congress, South Korea.

Ulusoy B., Griffin L.D., Mylonas, D. (2017). Turkish Colour Naming on the Net. In 13th AIC Congress, South Korea.

Paramei G, Gibber Y., Mylonas D. (2017) An online colour naming experiment in Russian using 
Munsell colour samples, Color Research & Application (in press), DOI:10.1002/col.22190.

**Comment by jstutters** [comment]
I've added these and closed the issue.  After version 1 we should look at moving the references to a separate markdown formatted file so they're easier to maintain.  The plan is for all updates to the site to be automatic when pushes are made to the master branch.

**Comment by dmylonas** [comment]
Sounds like a plan, cheers
