### ISSUE TITLE
Prolific data collection (Age and Colour Names)

### ISSUE THREAD

**Issue by akvilesinkeviciute** [colournaming/colournaming#226]
Thank you for your help in advance!
 If possible, could you: 
- [x] Increase the number of colour samples to 250.
- [ ] Resolve the issue of colour samples' repetition and/or update speed (two identical colour samples appear one after the other OR the samples do not change fast enough after naming the colour and pressing "enter". Can you please check this issue so it does not screw participants' response times and accuracy?)
- [x] Update participants_prolific_age to include a participant_id column (the columns should not overlap with responses_prolific_age. Only the participant_id column should be the same in both datasets to make it easy to join them together in Pandas)
- [x] Verify and update responses_prolific_age to retain only the participant_id column if id and participant_id are identical.
- [x] Add R, G, and B value columns next to target_id in responses_prolific_age.

**Comment by jstutters** [comment]
@akvilesinkeviciute current sample count on the production site appears to be 250, when was this tested and on which URL please?

![Screenshot from 2024-08-06 12-42-44](https://github.com/user-attachments/assets/a74180d7-27b1-41fc-bbd4-ae9626bfce9c)

**Comment by jstutters** [comment]
@akvilesinkeviciute please could you review https://devadmin.colornaming.net/results/joined_prolific_age_results and let me know if it resolves the last 3 points of this issue?

**Comment by jstutters** [comment]
Point 2 moved to issue #227

**Comment by akvilesinkeviciute** [comment]
> @akvilesinkeviciute current sample count on the production site appears to be 250, when was this tested and on which URL please?
> 
> ![Screenshot from 2024-08-06 12-42-44](https://private-user-images.githubusercontent.com/180336/355434545-a74180d7-27b1-41fc-bbd4-ae9626bfce9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDk3MTUsIm5iZiI6MTcyMjk0OTQxNSwicGF0aCI6Ii8xODAzMzYvMzU1NDM0NTQ1LWE3NDE4MGQ3LTI3YjEtNDFmYy1iYmQ0LWFlOTYyNmJmY2U5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMzAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGU2MjNlYTcyM2I3NTUzMGIxNGQyZjE2YTJiN2M1ZGQyYzA4OGM5ZGJhZDU3NWRhMDU5Mzg2ZGZmZjI5YjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1RHpYbPmXobBdemhSi-NjIjfgq_Go2wCfjUt0U7L0eg)

The older version that I accessed on 29th of July had only 226:
![Screenshot 2024-08-06 at 14 12 47](https://github.com/user-attachments/assets/a542e07b-c6fc-4d2b-ad40-d94112a3a306)
Now it is 250, thank you for fixing it!

**Comment by akvilesinkeviciute** [comment]
> @akvilesinkeviciute please could you review https://devadmin.colornaming.net/results/joined_prolific_age_results and let me know if it resolves the last 3 points of this issue?

@jstutters All good with the dataset now, thanks!

**Comment by jstutters** [comment]
I'll copy devadmin changes to production then close this issue.

**Comment by jstutters** [comment]
Production admin view changed to include combined results.
