### ISSUE TITLE
Colour sample repetition/update speed

### ISSUE THREAD

**Issue by jstutters** [colournaming/colournaming#227]
# Problem
Two identical colour samples appear one after the other OR the samples do not change fast enough after naming the colour and pressing "enter".

# Definition of done
- [ ] Participants are not presented with the same colour twice in a row
- [ ] (Optional) Prolific participants can be shown the whole target set one time in a random order

**Comment by akvilesinkeviciute** [comment]
@jstutters it seems that the issue persists. In the first case the colour sample does not change fast enough and in the second one the colour sample repeats twice: 

https://github.com/user-attachments/assets/a6cf49fb-3022-4625-a5e8-642a5114f700

https://github.com/user-attachments/assets/cf417ebb-9989-47a8-bcc1-a05d3d42dd16

**Comment by akvilesinkeviciute** [comment]
@jstutters what needs to be done for this to be fixed? how long do you think this will take?

**Comment by jstutters** [comment]
I don't know until I investigate. I'm planning to work on it tomorrow. If it's simple I'll fix it tomorrow, if not I should at least be able to guess how long it'll take to fix it

**Comment by jstutters** [comment]
@akvilesinkeviciute Please check the dev site again now.  Colour name input should be disabled while the new colour is loading.

@dmylonas please can you confirm which set of targets we're using for the age experiment: 226 or 606?

**Comment by akvilesinkeviciute** [comment]
Thank you @jstutters! I just want to confirm, am I accessing the correct version if I click 'Preview as a Participant' through the link you provided on Prolific?
<img width="253" alt="Screenshot 2024-08-10 at 15 21 31" src="https://github.com/user-attachments/assets/57ec2f7c-2061-4ee8-8745-8193e1553789">
I have no access to the dev site :(
I am still experiencing this issue (at least through Prolific): 
https://github.com/user-attachments/assets/9fd8588f-9ae2-4729-910d-d9f82b8160a9

**Comment by jstutters** [comment]
@akvilesinkeviciute You can test the dev site at this address: https://dev.colornaming.net/mturkage/start?PROLIFIC_PID=1001&STUDY_ID=4&SESSION_ID=5

Note that the fix doesn't remove the delay between colours (that's too complicated for a quick fix), instead it disables the inputs until a new colour is displayed.  The response time accounts for this.

**Comment by dmylonas** [comment]
Thank you both.
@jstutters The set of targets that we use for teh ageing study is the 606 set (original) but due to time limitations we will present only 250 out of 606 samples to each participant. The presentation fo each sample should be approximately balanced.  


> @akvilesinkeviciute Please check the dev site again now. Colour name input should be disabled while the new colour is loading.
> 
> @dmylonas please can you confirm which set of targets we're using for the age experiment: 226 or 606?

@jstutters The set of targets that we use for teh ageing study is the 606 set (original) but due to time limitations we will present only 250 out of 606 samples to each participant. The presentation fo each sample should be approximately balanced.

**Comment by dmylonas** [comment]
Thank you both.

The link that we have at Prolific that leads to https://colornaming.net/mturkage/ 
to name 250 colour samples is not working as it should be at the momment including delays of stimuli presenattion and repetitions of the same colour samples. 

I checked the new hack of Jon at dev site where we can name 10 colour samples, the video colour vision test is not working! but I named all 10 colours without delays or repetitions.
![Untitled](https://github.com/user-attachments/assets/bfc18824-2314-436e-b0c3-e06412acb6c5)

**Comment by akvilesinkeviciute** [comment]
@jstutters in the short version (https://dev.colornaming.net/mturkage/start?PROLIFIC_PID=1001&STUDY_ID=4&SESSION_ID=5), the colour vision test works fine for me. There were no delays, it seems. 

In the longer version (https://colornaming.net/mturkage/), same as @dmylonas I am still experiencing delays and repetitions.

I am wondering when was the longer version was last updated?

Many thanks!

**Comment by dmylonas** [comment]
This is not solved yet,the Prolific link is not working and the joined dataset is also missing

**Comment by akvilesinkeviciute** [comment]
@jstutters Can you please give me a link with the last version of the Prolific experiment with 250 colour samples? Thank you!

**Comment by jstutters** [comment]
@akvilesinkeviciute you can now access the version with 250 samples using the "Preview as participant" button at the bottom of the prolific project page.  The experiment URL for prolific is now updated to use the production version of the experiment with 250 samples.

The results will go to https://admin.colornaming.net/results/joined_prolific_age_results but note that the production results only update once per day.  The results in there now are from me testing it.
