### ISSUE TITLE
Colour vision test is not working on mobile version

### ISSUE THREAD

**Issue by akvilesinkeviciute** [colournaming/colournaming#236]
@jstutters a participant, who completed the Lithuanian version of the experiment on their phone, reported that the colour vision test did not work (the square did not move) and also noticed delays in the stimuli changing. I’m wondering if this issue occurs in other language mobile versions of the experiment as well.

**Comment by jstutters** [comment]
Tested and working on my phone in a couple of different languages.  This sounds much more likely to be a problem specific to this participant's phone or internet connection and not something we can fix.
