### ISSUE TITLE
Guarantee that all colour samples are presented equal times

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#25]

**Comment by jstutters** [comment]
@dmylonas it's random already so the presentation counts should balance out over time.  Do you need something more complicated than that?

**Comment by dmylonas** [comment]
@jstutters I know but in practice this is not the case. 
What we need is to construct an intermediate table where we can subtract each presented color_id and when we will present/subtract all 606 samples to load it again and so on

**Comment by jstutters** [comment]
@dmylonas do you want to do this for each participant or as a global thing?  Either's achievable but if you want it globally I need to make some modifications to the database schema.

**Comment by dmylonas** [comment]
I think a global thing will solve the problem: for example over time some samples have been presented 20 times while others only 10. Nobody is going to name more than 606 samples.
