### ISSUE TITLE
Submit button on observer information does not trigger a post request

### ISSUE THREAD

**Issue by jstutters** [colournaming/colournaming#30]
Not sure when this broke.  I've updated the form element IDs but that doesn't seem to have fixed the problem.

**Comment by chrisguttandin** [comment]
I think it's because there is no field called `educational_level` it seems to be called `education_level`. Changing it [here](https://github.com/colournaming/colournaming/blob/master/colournaming/static/js/experiment.js#L189) should work.

**Comment by jstutters** [comment]
That is an error but the problem's actually [https://github.com/colournaming/colournaming/blob/master/colournaming/static/js/experiment.js#L314](on line 314) I think.  submitForm is sending to the thankyou page URL not the observer information URL (which is where the POST should go).  Can the Javascript be adjusted to POST to /experiment/observer_information.html and follow the redirect that it'll get or do I need to make /experiment/thankyou.html accept a POSTed observer information form?

**Comment by chrisguttandin** [comment]
`submitForm()` always submits the form to the window's current location. (https://github.com/colournaming/colournaming/blob/master/colournaming/static/js/experiment.js#L21). The second argument is the redirect location which is used to redirect the page after a successful form submission.

**Comment by jstutters** [comment]
Thanks for the help. After some struggling I got this sorted in https://github.com/colournaming/colournaming/commit/e38bbc5ea501ae02c425fbcba6cd478c7d1b91a9
