### ISSUE TITLE
link Twitter/fb/mail buttons in homepage and thank you page

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#31]

**Comment by jstutters** [comment]
Can you provide the links?

**Comment by dmylonas** [comment]
I don't know if they work properly but here u are:
Twitter:
<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Let&#39;s play a game, how many colours can you name?" data-via="colornaming" data-hashtags="colournamer" data-related="" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Facebook:
<a href="https://www.facebook.com/sharer/sharer.php?u=colornaming.net" target="_blank">
</a>
It should be fetching the mobiles.jpg image
with the title: Colour Naming Experiment
and discription: Let's play a game, how many colours can you name?
and link: colornaming.net

Mail:
<a href="mailto:?subject=How many colours can you name?&amp;body=Let's play a game, how many colours can you name at http://www.colornaming.net ?"
   title="Share by Email">
  <img src="...">
</a>

**Comment by jstutters** [comment]
Front page social link hrefs fixed by https://github.com/colournaming/colournaming/commit/3b03c2bd95bbdca523ebec70cdd6d90c4184afe8
