### ISSUE TITLE
Namer sound responses

### ISSUE THREAD

**Issue by jstutters** [colournaming/colournaming#41]

**Comment by dmylonas** [comment]
on iphone for all browsers the sounds are muted

**Comment by jstutters** [comment]
@chrisguttandin Any idea about why we're not getting sound on iOS Safari?  I haven't got access to a Mac untli tomorrow to debug this.

**Comment by chrisguttandin** [comment]
Does it work in any other browser? It doesn't work for me in Chrome as well.
