### ISSUE TITLE
Styling ColourNamer for both desktops & mobiles

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#5]

**Comment by jstutters** [comment]
@chrisguttandin does merging #26 mean that we can close this issue or are there still styling tasks to do?

**Comment by chrisguttandin** [comment]
Yes, I think so.

**Comment by dmylonas** [comment]
You have not embed Colornamer yet in our homepage

**Comment by jstutters** [comment]
@chrisguttandin is that something you can handle or do I need to do it?

**Comment by chrisguttandin** [comment]
I thought I already saw a styled version of the colournamer. But apparently the version at /namer/interface does look differently. Is there maybe another version somewhere else?

**Comment by jstutters** [comment]
I'm not having much luck finding it. Any chance you've got a local copy?

**Comment by chrisguttandin** [comment]
I was thinking of this version: http://colournaming.com/research/

**Comment by jstutters** [comment]
In that case we're short of a styled version of the colour namer.  The mobile version's in an ok state but the large-screen version needs work.

**Comment by dmylonas** [comment]
[colornamer_17.pdf](https://github.com/colournaming/colournaming/files/1381055/colornamer_17.pdf)
I can see that the current interface is difficult to style it for mobiles, what about this one?
