### ISSUE TITLE
Contact Form - Submit button is not working

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#67]
when a user presses submit will see this:
Method Not Allowed
The method is not allowed for the requested URL.

**Comment by dmylonas** [comment]
@chrisguttandin can you deal with this?

**Comment by chrisguttandin** [comment]
@jstutters the form gets currently posted to the root (/) because no url was specified. Should it be send to a certain endpoint?

**Comment by jstutters** [comment]
Now working on dev.colornaming.net and configured to work on production site when code is deployed.

**Comment by dmylonas** [comment]
@jstutters  I've tried to submit a message but I didn't get the test email, even in my spam folder. 
(Previously, I've filtered emails coming from the website to a different folder and skiped the spam folder - although I do get a notification that they might be a spam.)
In addition, the user is not currently informed that their message was sent and the form is not cleared for a new message.

**Comment by jstutters** [comment]
@dmylonas I've adjusted some postfix settings that I think will get the emails to come through on gmail now.  Form clearing and a confirmation is still to do.
