### ISSUE TITLE
Solve javascript problems with iPhone 7

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#68]
Problems:
1. Experiment doesn't move one after a user selects an option for the steps of the greyscale ramp
2. In the thank you page (last step), users don't get the results

Devices: old iPhones and iPads and iPhone 7
Browsers: both Safari and Chrome

**Comment by dmylonas** [comment]
@chrisguttandin @jstutters is there anything else that we can do for cross browser/device compatibility? can we check it on any iphoneX device/simulator?

**Comment by chrisguttandin** [comment]
I think transpiling the JavaScript to ES5 will solve the problem.

**Comment by dmylonas** [comment]
just got another feedback that while the user can do the task at the end the results are missing, that might mean that we don't save them in the database

**Comment by jstutters** [comment]
I'm working on this in the [webpack branch](https://github.com/colournaming/colournaming/tree/webpack).  The namer's ok but I need to add the javascript for the experiment.  Contributions welcome if either of you know your way around webpack.

**Comment by jstutters** [comment]
@dmylonas can you check the [webpack branch](https://github.com/colournaming/colournaming/tree/webpack) to make sure the experiment and namer are still working?  If it's alright for you in local testing I'll merge this with the develop branch so we can check on https://dev.colornaming.net with some other devices.

**Comment by jstutters** [comment]
Closing this.  We're transpiling to ES5 now which should solve most issues.  If there are any remaining issues with specific versions of Android or iOS a device will be needed to test.
