### ISSUE TITLE
Plug options of dropdown menus to python

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#7]

**Comment by dmylonas** [comment]
in multiple languages

**Comment by dmylonas** [comment]
full list of countries in residency and place grown up

**Comment by jstutters** [comment]
Working on this in the [form-template-link](https://github.com/colournaming/colournaming/tree/form-template-link) branch.

**Comment by dmylonas** [comment]
can you please sort the countries AB

**Comment by jstutters** [comment]
> can you please sort the countries AB

Fixed by https://github.com/colournaming/colournaming/commit/04cd7fae4594d9015e5a9f7eb63b032074608ea9.
