### ISSUE TITLE
Sound (voice) of Colour namer in mobiles

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#71]
Colournamer is voiceless in mobiles.
It seems that the app 'may be' is auto muted by the browser. 
If we will add a button to enable/disable the sound of the app is it going to work?

**Comment by dmylonas** [comment]
@chrisguttandin Colournamer is voiceless in mobiles, can we do something about it? As far as I know the browsers shut off the voice by default in mobiles  unless the user activates it, can we add a button sound ON/OFF button?

**Comment by jstutters** [comment]
Fixed by c5f083b487d20e24dbb4e7c9207a18ae6db77d5d (at least for the latest iOS).
