### ISSUE TITLE
Fix n% relative to number of responses

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#72]
The n% in the thank you page that should be related to the number of responses is not working properly:
When I submitted 6 responses I got 71% and when I submitted 3 responses I got 82%, then I submitted 1 and I got 100% and when I submitted 4 I got 71%.

The way that should work would be: the higher the number of responses, the higher the rank (n%)

**Comment by dmylonas** [comment]
@jstutters

**Comment by jstutters** [comment]
@dmylonas can you have a look at https://dev.colornaming.net and confirm that it's now behaving as you expect?

**Comment by dmylonas** [comment]
when I named 1 and 26 patches I got 0% in both cases. So no it is not behaving well.

**Comment by dmylonas** [comment]
What we should count here is the number of colours named by each user relative to the number of responses of each user

**Comment by dmylonas** [comment]
@jstutters what might be easier & clearer is to rank each user based on the number of their responses, so instead of % we could use 1st, 2nd, 127th and so on

**Comment by dmylonas** [comment]
hmm, let's assume then that the best colour namer will name all unique colours and set the maximum number equal to the length of our colour array, then divide the number of responses of each user by this number and multiply it by 100 (%). This should be cheap and representative!

**Comment by jstutters** [comment]
Good suggestion.
