### ISSUE TITLE
update Observer Information

### ISSUE THREAD

**Issue by dmylonas** [colournaming/colournaming#76]
What is your age?
[15- to 100+]

To which gender do you most identify?
[Female/Male/Other]

When the user selects 'Other' a new input text field should appear asking them:
Please specify [ ]

Describe your experience working with colour?
[Beginner/Intermediate/Advanced]

Describe your skill in the language used in this experiment?
[Beginner/Intermediate/Advanced/Native Speaker/Bilingual]

What is the highest level of education you have completed?
[-/No qualifications/Secondary School degree/Bachelor’s degree /Master’s degree /Professional degree/Doctorate degree]

Where did you grow up?
[list of countries]

Where are you living?
[list of countries]

What is your display device?
[- / Smartphone / Pad / Laptop / Desktop]

Describe the white graphic elements on your screen?
[-/Neutral White/Warm White/Bluish White/Yellowish White]

Describe the surrounding environment behind your device?
[-/Dark/Dim/Average/Bright]

Describe the lighting conditions of your environment?
[-/Typical Domestic/Typical Office/Dark/Mid Daylight/Full Daylight]

What is your distance from your display device?
[10-cm to 100+cm]

**Comment by dmylonas** [comment]
@jstutters this one the final questionaire

**Comment by jstutters** [comment]
@dmylonas can you check https://dev.colornaming.net and let me know if the updated form is ok now?

**Comment by dmylonas** [comment]
only one point: distance should be from 10- to 100+ cm
